import React, { ReactNode } from "react";
import Head from "next/head";
import Header from "./Header";
import { useRouter } from "next/router";

type props = {
  children: ReactNode;
};

const Layout = ({ children }: props) => {
  const router = useRouter();
  return (
    <div className="layout">
      <Head>
        <title>Books & Reviews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={router.pathname.includes("book") ? "" : "full-screen-div"}>
        <Header />
        <main className="sticky-padding">{children}</main>
      </div>
    </div>
  );
};

export default Layout;
