import React, { ReactNode } from "react";
import Head from "next/head";
import { NextPage } from "next";
import Header from "./Header";

type props = {
  children: ReactNode;
};

const Layout: NextPage<props> = ({ children }) => {
  return (
    <div className="layout">
      <Head>
        <title>Books & Reviews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="full-screen-div">
        <Header />
        <main className="sticky-padding">{children}</main>
      </div>
    </div>
  );
};

export default Layout;
